<?php
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;

/**
 *
 * @file
 * Primary module hooks for rating_app module.
 */

/**
 * implement hook_entity_base_field_info
 * ND: il faut executer "drush entup" pour que les champs soit MAJ dans la bd.
 *
 * @param EntityTypeInterface $entity_type
 *
 */
function rating_app_entity_base_field_info(EntityTypeInterface $entity_type) {
  $fields = [];
  if ($entity_type->id() == 'vote') {
    /**
     * Permet de relier le vote à un commentaire
     */
    $fields['rating_app_comment_id'] = BaseFieldDefinition::create('entity_reference')->setLabel(t(' Comment id'))->setDisplayOptions('form', [ //
    ])->setSetting('target_type', 'comment')->setSetting('handler', 'default')->setDisplayOptions('view', [ //
    ])->setDisplayConfigurable('form', true)->setDisplayConfigurable('view', TRUE);
  }
  return $fields;
}