<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\node\NodeTypeInterface;
use Drupal\node\Entity\Node;

function crea_pagelle_node_presave(EntityInterface $entity) {

    $entity_type = 'node';
    $bundles = ['partita_di_calcio'];

    if ($entity->getEntityTypeId() != $entity_type || !in_array($entity->bundle(), $bundles)) {
      return;
    }
    if ( $entity->field_crea_pagelle->value && !$entity->field_pagelle_create->value){

        $bianchi = $entity->field_bianchi->referencedEntities();
        $neri = $entity->field_neri->referencedEntities();
        if(is_array($bianchi)){
            foreach ($bianchi as &$value) {
                // Create a new node object.
                $node = Node::create([
                    'type' => 'pagella_partita',
                    'title' => 'Pagella del '. date("d-m", strtotime($entity->field_data->value)),
                    'field_giocatore' => $value,
                    'field_partita' => $entity,
                    'uid' => $value,
                    //'field_pagelle_create' => true,
                ]);
                // Save the node.
                $node->save();

                $items = \Drupal::entityTypeManager()->getStorage('node')
                ->loadByProperties(['type' => 'pagelle_del_calciatore',
                                    'field_giocatore' => $value->uid->value,]);

                if (empty($items)) {
                    $pagella_di = Node::create([
                        'type' => 'pagelle_del_calciatore',
                        'title' => 'Pagelle di '. $value->name->value,
                        'field_giocatore' => $value,
                        'uid' => $value,
                        //'field_pagelle_create' => true,
                    ]);
                    // Save the node.
                    $pagella_di->save();
                    $pagella_di->nid = $pagella_di->id();
                    $pagella_di->field_pagelle[] = ['target_id' => $node->id()];
                    $pagella_di->save();
                }else{
                    //array_push(reset($items)->field_pagelle->referencedEntities(), $node->nid);
                    //$node->field_code_used_by[] = ['target_id' => $user_id];
                    $pagelle_del_calciatore=reset($items);
                    $pagelle_del_calciatore->field_pagelle[] = ['target_id' => $node->id()];
                    $pagelle_del_calciatore->save();
                }

            }
        }

        if(is_array($neri)){
            foreach ($neri as &$value) {
                // Create a new node object.
                $node = Node::create([
                    'type' => 'pagella_partita',
                    'title' => 'Pagella del '. date("d-m", strtotime($entity->field_data->value)),
                    'field_giocatore' => $value,
                    'field_partita' => $entity,
                    'uid' => $value,
                    //'field_pagelle_create' => true,
                ]);
                // Save the node.
                $node->save();

                $items = \Drupal::entityTypeManager()->getStorage('node')
                ->loadByProperties(['type' => 'pagelle_del_calciatore',
                                    'field_giocatore' => $value->uid->value,]);

                if (empty($items)) {
                    $pagella_di = Node::create([
                        'type' => 'pagelle_del_calciatore',
                        'title' => 'Pagelle di '. $value->name->value,
                        'field_giocatore' => $value,
                        'uid' => $value,
                        //'field_pagelle_create' => true,
                    ]);
                    // Save the node.
                    $pagella_di->save();
                    $pagella_di->nid = $pagella_di->id();
                    $pagella_di->field_pagelle[] = ['target_id' => $node->id()];
                    $pagella_di->save();
                }else{
                    //array_push(reset($items)->field_pagelle->referencedEntities(), $node->nid);
                    //$node->field_code_used_by[] = ['target_id' => $user_id];
                    $pagelle_del_calciatore=reset($items);
                    $pagelle_del_calciatore->field_pagelle[] = ['target_id' => $node->id()];
                    $pagelle_del_calciatore->save();
                }
            }
        }
        $entity->field_pagelle_create->value=1;
    }


}

function crea_pagelle_entity_update(EntityInterface $entity) {
    $entity_type = 'node';
    $bundles = ['partita_di_calcio'];

    if ($entity->getEntityTypeId() != $entity_type || !in_array($entity->bundle(), $bundles)) {
      return;
    }
    /*
    if ( $entity->field_crea_pagelle->value && !$entity->field_pagelle_create->value){

        $bianchi = $entity->field_bianchi->referencedEntities();
        $neri = $entity->field_neri->referencedEntities();
        if(is_array($bianchi)){
            foreach ($bianchi as &$value) {
                // Create a new node object.
                $node = Node::create([
                    'type' => 'pagella_partita',
                    'title' => 'Pagella del '. date("d-m", strtotime($entity->field_data->value)),
                    'field_giocatore' => $value,
                    'field_partita' => $entity,
                    'uid' => $value,
                    //'field_pagelle_create' => true,
                ]);
                // Save the node.
                $node->save();

                $items = \Drupal::entityTypeManager()->getStorage('node')
                ->loadByProperties(['type' => 'pagelle_del_calciatore',
                                    'field_giocatore' => $value->uid->value,]);

                if (empty($items)) {
                    $pagella_di = Node::create([
                        'type' => 'pagelle_del_calciatore',
                        'title' => 'Pagelle di '. $value->name,
                        'field_giocatore' => $value,
                        'uid' => $value,
                        //'field_pagelle_create' => true,
                    ]);
                    // Save the node.
                    $pagella_di->save();
                    $pagella_di->nid = $pagella_di->id();
                    $pagella_di->field_pagelle[] = ['target_id' => $node->id()];
                    $pagella_di->save();
                }else{
                    //array_push(reset($items)->field_pagelle->referencedEntities(), $node->nid);
                    //$node->field_code_used_by[] = ['target_id' => $user_id];
                    $pagelle_del_calciatore=reset($items);
                    $pagelle_del_calciatore->field_pagelle[] = ['target_id' => $node->id()];
                    $pagelle_del_calciatore->save();
                }

            }
        }

        if(is_array($neri)){
            foreach ($neri as &$value) {
                // Create a new node object.
                $node = Node::create([
                    'type' => 'pagella_partita',
                    'title' => 'Pagella del '. date("d-m", strtotime($entity->field_data->value)),
                    'field_giocatore' => $value,
                    'field_partita' => $entity,
                    'uid' => $value,
                    //'field_pagelle_create' => true,
                ]);
                // Save the node.
                $node->save();

                $items = \Drupal::entityTypeManager()->getStorage('node')
                ->loadByProperties(['type' => 'pagelle_del_calciatore',
                                    'field_giocatore' => $value->uid->value,]);

                //array_push(reset($items)->field_pagelle->referencedEntities(), $node->nid);
                //$node->field_code_used_by[] = ['target_id' => $user_id];
                $pagelle_del_calciatore=reset($items);
                $pagelle_del_calciatore->field_pagelle[] = ['target_id' => $node->id()];
                $pagelle_del_calciatore->save();
            }
        }
    }
    */

  }